spring.application.name=RealTimeChat-backend

spring.datasource.url=jdbc:mysql://localhost:3306/realtimechat
spring.datasource.username=root
spring.datasource.password=1011

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=IYcD2/Y39orfWVYNPCXq9P1E4NiGT5S6H2+SWXCM/3JryeWJ82hdjy6S8Ni0w1BD
jwt.expiration=900000
logging.level.org.springframework.security=DEBUG